2018-05-12 17:21:35,880 parameterhelper INFO     Loading config for dimensionality as a percentage of the reservoir size.
2018-05-12 17:21:35,881 parameterhelper INFO     Config: ./configs/user/bayeridge_rpca (overload)
2018-05-12 17:21:35,881 root            INFO     Loading data (./data/Sunspots)
2018-05-12 17:21:35,922 root            INFO     Initializing genetic algorithm
2018-05-12 17:21:35,923 root            INFO     Running GA optimization
/usr/local/lib/python3.5/dist-packages/scoop/fallbacks.py:46: RuntimeWarning: SCOOP was not started properly.
Be sure to start your program with the '-m scoop' parameter. You can find further information in the documentation.
Your map call has been replaced by the builtin serial Python map().
  RuntimeWarning
A: [[ 0.0134204   0.05527016  0.01785354 ... -0.03038987  0.02033206
  -0.01726028]
 [ 0.01871338  0.0546848   0.00344794 ... -0.02529976  0.0531501
  -0.00466525]
 [ 0.02176121  0.02168704 -0.01271154 ... -0.02220591 -0.01132265
  -0.00401715]
 ...
 [ 0.00570952 -0.011635   -0.00398106 ... -0.01284984  0.00543995
  -0.009807  ]
 [ 0.00454937 -0.01153528  0.00440567 ...  0.00684206  0.00676994
  -0.00236044]
 [ 0.03261755 -0.01545048 -0.00743744 ... -0.01566423  0.00210135
  -0.00833934]]
Traceback (most recent call last):
  File "./genoptesn.py", line 385, in <module>
    main()
  File "./genoptesn.py", line 374, in main
    lambda_ = n_offsprings, cxpb=cxpb, mutpb=mutpb, ngen=ngen, stats=stats, verbose=True, halloffame=halloffame)
  File "/usr/local/lib/python3.5/dist-packages/deap/algorithms.py", line 304, in eaMuPlusLambda
    for ind, fit in zip(invalid_ind, fitnesses):
  File "./genoptesn.py", line 268, in evaluate_ind
    _, errors[i] = esnet.run_from_config(Xtr, Ytr, Xval, Yval, parameters, Yscaler)
  File "/home/minh/PycharmProjects/MultivariateESN/esnet.py", line 340, in run_from_config
    embedding = embedding, n_dim = n_dim, embedding_parameters = embedding_parameters)
  File "/home/minh/PycharmProjects/MultivariateESN/esnet.py", line 68, in fit
    _,_ = self._fit_transform(Xtr = Xtr, Ytr = Ytr, n_drop = n_drop, regression_method = regression_method, regression_parameters = regression_parameters, embedding = embedding, n_dim = n_dim, embedding_parameters = embedding_parameters)
  File "/home/minh/PycharmProjects/MultivariateESN/esnet.py", line 187, in _fit_transform
    states, embedded_states,_ = self._compute_state_matrix(X = Xtr, Y = Ytr, n_drop = n_drop)
  File "/home/minh/PycharmProjects/MultivariateESN/esnet.py", line 277, in _compute_state_matrix
    embedded_states = self._embedding_method.fit_transform(state_matrix)
  File "/home/minh/PycharmProjects/MultivariateESN/RobustPCA.py", line 162, in fit_transform
    Z = self.__l1_prox(Xt - Y - W, self.alpha_ / rho)
  File "/home/minh/PycharmProjects/MultivariateESN/RobustPCA.py", line 64, in __l1_prox
    if (A[i]-r > 0):
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
[2018-05-12 17:21:36,107] launcher  INFO    SCOOP 0.7 1.1 on linux using Python 3.5.2 (default, Nov 23 2017, 16:37:01) [GCC 5.4.0 20160609], API: 1013
[2018-05-12 17:21:36,107] launcher  INFO    Deploying 8 worker(s) over 1 host(s).
[2018-05-12 17:21:36,107] launcher  INFO    Worker distribution: 
[2018-05-12 17:21:36,107] launcher  INFO       127.0.0.1:	7 + origin
[Errno 2] No such file or directory: './configs/esn/Sunspots_bayeridge_rpca.json'
File: ./esn_experiment.py
In path: /home/minh/PycharmProjects/MultivariateESN
[Errno 2] No such file or directory: './configs/esn/Sunspots_bayeridge_rpca.json'
File: ./esn_experiment.py
In path: /home/minh/PycharmProjects/MultivariateESN
[Errno 2] No such file or directory: './configs/esn/Sunspots_bayeridge_rpca.json'
File: ./esn_experiment.py
In path: /home/minh/PycharmProjects/MultivariateESN
[Errno 2] No such file or directory: './configs/esn/Sunspots_bayeridge_rpca.json'
File: ./esn_experiment.py
In path: /home/minh/PycharmProjects/MultivariateESN
[Errno 2] No such file or directory: './configs/esn/Sunspots_bayeridge_rpca.json'
File: ./esn_experiment.py
In path: /home/minh/PycharmProjects/MultivariateESN
[Errno 2] No such file or directory: './configs/esn/Sunspots_bayeridge_rpca.json'
File: ./esn_experiment.py
In path: /home/minh/PycharmProjects/MultivariateESN
[2018-05-12 17:21:36,658] launcher  (127.0.0.1:38607) INFO    Root process is done.
[2018-05-12 17:21:36,659] launcher  (127.0.0.1:38607) INFO    Finished cleaning spawned subprocesses.
